[build.environment]
  NODE_VERSION = "16"
  # don't need playwright for docs build
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
[build]
  publish = "docs/.vitepress/dist"
  command = "rm -rf node_modules && pnpm i && pnpm ci-docs"
  ignore = "./scripts/docs-check.sh"
